<?php
require_once 'db.php';

// USERS
$pdo->exec("
CREATE TABLE IF NOT EXISTS users (
  id_user INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password TEXT NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)");

// LISTS
$pdo->exec("
CREATE TABLE IF NOT EXISTS lists (
  id_list INT AUTO_INCREMENT PRIMARY KEY,
  list_name VARCHAR(255) NOT NULL,
  description TEXT DEFAULT 'No description',
  is_active BOOLEAN DEFAULT TRUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  user_id INT,
  FOREIGN KEY (user_id) REFERENCES users(id_user) ON DELETE CASCADE
)");

// PRODUCTS
$pdo->exec("
CREATE TABLE IF NOT EXISTS products (
  id_product INT AUTO_INCREMENT PRIMARY KEY,
  product_name VARCHAR(255) UNIQUE NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)");

// PURCHASES
$pdo->exec("
CREATE TABLE IF NOT EXISTS purchases (
  id_purchase INT AUTO_INCREMENT PRIMARY KEY,
  description TEXT DEFAULT 'No description',
  number INT NOT NULL,
  unit VARCHAR(50) NOT NULL,
  unit_price DECIMAL(10,2) DEFAULT 0.00,
  total_price DECIMAL(10,2) GENERATED ALWAYS AS (number * unit_price) STORED,
  purchase_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  list_id INT,
  product_id INT,
  FOREIGN KEY (list_id) REFERENCES lists(id_list) ON DELETE CASCADE,
  FOREIGN KEY (product_id) REFERENCES products(id_product) ON DELETE SET NULL
)");
?>
